spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interview_platform_dev
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true