spring:
  profiles:
    active: dev
  application:
    name: interview-platform
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa:
      repositories:
        enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG